<?php

return [
    [
        'name' => 'Pizza Margherita',
        'ingredients_descriptions' => 'Pomodoro, mozzarella, basilico, olio d\'oliva',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 8.99,
        'visible' => true,
    ],
    [
        'name' => 'Spaghetti alla Carbonara',
        'ingredients_descriptions' => 'Spaghetti, uova, pancetta, pecorino, pepe',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 12.50,
        'visible' => true,
    ],
    [
        'name' => 'Lasagna alla Bolognese',
        'ingredients_descriptions' => 'Sfoglia di pasta, ragù di carne, besciamella, Parmigiano Reggiano',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 14.00,
        'visible' => true,
    ],
    [
        'name' => 'Penne all\'Arrabbiata',
        'ingredients_descriptions' => 'Penne, pomodoro, peperoncino, aglio, prezzemolo',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 9.50,
        'visible' => true,
    ],
    [
        'name' => 'Risotto ai Funghi',
        'ingredients_descriptions' => 'Riso, funghi porcini, burro, Parmigiano Reggiano, prezzemolo',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 13.20,
        'visible' => true,
    ],
    [
        'name' => 'Tagliatelle al Ragù',
        'ingredients_descriptions' => 'Tagliatelle, ragù di carne, Parmigiano Reggiano',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 12.00,
        'visible' => true,
    ],
    [
        'name' => 'Trofie al Pesto',
        'ingredients_descriptions' => 'Trofie, pesto genovese, patate, fagiolini',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 11.00,
        'visible' => true,
    ],
    [
        'name' => 'Gnocchi al Pomodoro',
        'ingredients_descriptions' => 'Gnocchi di patate, salsa di pomodoro, Parmigiano Reggiano',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 9.80,
        'visible' => true,
    ],
    [
        'name' => 'Ravioli di Ricotta e Spinaci',
        'ingredients_descriptions' => 'Ravioli, ricotta, spinaci, burro, salvia',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 12.50,
        'visible' => true,
    ],
    [
        'name' => 'Pollo alla Cacciatora',
        'ingredients_descriptions' => 'Pollo, pomodori, olive, rosmarino, vino bianco',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 15.00,
        'visible' => true,
    ],
    [
        'name' => 'Fettuccine Alfredo',
        'ingredients_descriptions' => 'Fettuccine, burro, Parmigiano Reggiano',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 10.00,
        'visible' => true,
    ],
    [
        'name' => 'Pizza Diavola',
        'ingredients_descriptions' => 'Pomodoro, mozzarella, salame piccante, peperoncino',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 9.99,
        'visible' => true,
    ],
    [
        'name' => 'Insalata Caprese',
        'ingredients_descriptions' => 'Mozzarella di bufala, pomodori, basilico, olio d\'oliva',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 8.50,
        'visible' => true,
    ],
    [
        'name' => 'Polenta con Salsiccia',
        'ingredients_descriptions' => 'Polenta, salsiccia, salsa di pomodoro, Parmigiano',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 13.50,
        'visible' => true,
    ],
    [
        'name' => 'Ossobuco alla Milanese',
        'ingredients_descriptions' => 'Ossobuco, risotto alla milanese, burro, zafferano',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 18.00,
        'visible' => true,
    ],
    [
        'name' => 'Pizza Quattro Stagioni',
        'ingredients_descriptions' => 'Pomodoro, mozzarella, carciofi, funghi, prosciutto cotto, olive',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 12.00,
        'visible' => true,
    ],
    [
        'name' => 'Risotto alla Milanese',
        'ingredients_descriptions' => 'Riso, zafferano, burro, Parmigiano',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 11.50,
        'visible' => true,
    ],
    [
        'name' => 'Zuppa di Pesce',
        'ingredients_descriptions' => 'Pesce misto, pomodoro, aglio, prezzemolo',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 16.50,
        'visible' => true,
    ],
    [
        'name' => 'Spaghetti alle Vongole',
        'ingredients_descriptions' => 'Spaghetti, vongole, aglio, olio d\'oliva, prezzemolo',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 14.00,
        'visible' => true,
    ],
    [
        'name' => 'Melanzane alla Parmigiana',
        'ingredients_descriptions' => 'Melanzane, salsa di pomodoro, mozzarella, Parmigiano Reggiano',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 10.50,
        'visible' => true,
    ],
    [
        'name' => 'Pizza Quattro Formaggi',
        'ingredients_descriptions' => 'Pomodoro, mozzarella, gorgonzola, Parmigiano, fontina',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 11.00,
        'visible' => true,
    ],
    [
        'name' => 'Frittura di Calamari',
        'ingredients_descriptions' => 'Calamari fritti, limone, olio',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 13.00,
        'visible' => true,
    ],
    [
        'name' => 'Tiramisù',
        'ingredients_descriptions' => 'Mascarpone, caffè, cacao, biscotti savoiardi',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 5.50,
        'visible' => true,
    ],
    [
        'name' => 'Panna Cotta',
        'ingredients_descriptions' => 'Panna, zucchero, gelatina, vaniglia',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 5.00,
        'visible' => true,
    ],
    [
        'name' => 'Crema Catalana',
        'ingredients_descriptions' => 'Crema di vaniglia, caramello, scorza di limone',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 6.00,
        'visible' => true,
    ],
    [
        'name' => 'Budino al Cioccolato',
        'ingredients_descriptions' => 'Budino al cioccolato, panna montata',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 5.50,
        'visible' => true,
    ],
    [
        'name' => 'Crostata di Frutta',
        'ingredients_descriptions' => 'Pasta frolla, crema pasticcera, frutta fresca',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 6.50,
        'visible' => true,
    ],
    [
        'name' => 'Gelato alla Vaniglia',
        'ingredients_descriptions' => 'Gelato artigianale alla vaniglia',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 4.50,
        'visible' => true,
    ],
    [
        'name' => 'Gelato al Cioccolato',
        'ingredients_descriptions' => 'Gelato artigianale al cioccolato',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 4.50,
        'visible' => true,
    ],
    [
        'name' => 'Gelato alla Nocciola',
        'ingredients_descriptions' => 'Gelato artigianale alla nocciola',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 4.50,
        'visible' => true,
    ],
    [
        'name' => 'Cappuccino',
        'ingredients_descriptions' => 'Caffè, latte, schiuma di latte',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 3.50,
        'visible' => true,
    ],
    [
        'name' => 'Espresso',
        'ingredients_descriptions' => 'Caffè forte e aromatico',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 2.00,
        'visible' => true,
    ],
    [
        'name' => 'Tè Verde',
        'ingredients_descriptions' => 'Tè verde, aromatizzato con limone',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 2.50,
        'visible' => true,
    ],
    [
        'name' => 'Frullato di Frutta',
        'ingredients_descriptions' => 'Frutta fresca, latte, zucchero',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 4.00,
        'visible' => true,
    ],
    [
        'name' => 'Acqua Naturale',
        'ingredients_descriptions' => 'Acqua minerale naturale',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 1.50,
        'visible' => true,
    ],
    [
        'name' => 'Acqua Frizzante',
        'ingredients_descriptions' => 'Acqua minerale frizzante',
        'img' => 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        'price' => 1.50,
        'visible' => true,
    ],
];
